package sn.gtech.sgle.entity.enums;

public enum TypeNotificationEnum {
    ATTRIBUTION_LOGEMENT,
    DEMANDE_APPROUVEE,
    DEMANDE_REJETEE,
    RAPPEL_PAIEMENT,
    INCIDENT_RESOLU,
    REPONSE_INCIDENT,
    FIN_CONTRAT_PROCHE,
    MAINTENANCE_PLANIFIEE,
    MAINTENANCE_PROGRAMMEE,
    MESSAGE_GESTIONNAIRE,
    INFORMATION_GENERALE,
    DOCUMENT_EXPIRE,
    BIENVENUE,
    ALERTE_SYSTEME
}
